bsp: imx6ulevk: fix building for lf-5.10.y
The MAILBOX option is required by IMX_RPMSG to avoid getting a
linking error [1].

[1]
 | arm-lmp-linux-gnueabi-ld.bfd: imx_rpmsg.c:(.text+0x40c): undefined reference to `mbox_request_channel_byname'
 | arm-lmp-linux-gnueabi-ld.bfd: imx_rpmsg.c:(.text+0x550): undefined reference to `mbox_free_channel'
 | arm-lmp-linux-gnueabi-ld.bfd: imx_rpmsg.c:(.text+0x560): undefined reference to `mbox_free_channel'
 | arm-lmp-linux-gnueabi-ld.bfd: imx_rpmsg.c:(.text+0x6a4): undefined reference to `mbox_request_channel_byname'
 | arm-lmp-linux-gnueabi-ld.bfd: imx_rpmsg.c:(.text+0x734): undefined reference to `mbox_free_channel'
 | arm-lmp-linux-gnueabi-ld.bfd: imx_rpmsg.c:(.text+0x770): undefined reference to `mbox_free_channel'
 | make[1]: *** [build/tmp-lmp/work-shared/imx6ullevk/kernel-source/Makefile:1178: vmlinux] Error 1

Fixes: ae856ed ("bsp: imx: add initial bsp definition for imx6ulevk")
Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>