bsp: imx7ulpea-ucom: fix building for lf-5.10.y
The PCIE_HOST option is required to avoid getting a linking error [1].

[1]
| arm-lmp-linux-gnueabi-ld.bfd: pci-imx6.c:(.text+0x970): undefined reference to `dw_pcie_write_dbi'
| arm-lmp-linux-gnueabi-ld.bfd: pci-imx6.c:(.text+0x9ac): undefined reference to `dw_pcie_read_dbi'
| arm-lmp-linux-gnueabi-ld.bfd: pci-imx6.c:(.text+0x9c0): undefined reference to `dw_pcie_write_dbi'

Signed-off-by: Vanessa Maegima <vanessa.maegima@foundries.io>